import "./globals.css";
import localfont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SessionWrapper from "@/components/Sessionwrapper";

const gazpacho = localfont({src:"./gazpacho.ttf"});


export const metadata = {
  title: "Rupamdas",
  description: "Generated by Rupam Das",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${gazpacho.className}`}>
        <SessionWrapper >
          <Header />
          <Navbar />
          {children}
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
